package util;

public enum View {
	HOME,
	ADMIN_LOGIN, ADMIN_HOME,
	PROD_INSERT, PROD_UPDATE, PROD_DEL, PROD_LIST,
	PROD_BUY, 
	CART_ADD, CART_ADD_TEMP, CART_LIST, CART_TEMP,
	MEMBER, MEMBER_LOGIN, MEMBER_JOIN, MEMBER_UPDATE, MEMBER_OUT
	
	
	
}
